import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
export default defineConfig({
  site: 'https://devisv505.github.io',
  base: '/Sound-Manager-Doc',
  trailingSlash: 'always',
  output: 'static',
  integrations: [
    starlight({
      title: 'Sound Manager',
      description: 'Small scenes. Expressive sound. The DEV505 Sound Manager documentation.',
      favicon: '/favicon.svg',
      customCss: ['./src/styles/theme.css'],
      credits: false,
      disable404Route: false,
      components: {
        Header: './src/components/Header.astro',
        PageTitle: './src/components/PageTitle.astro',
        Footer: './src/components/Footer.astro',
        ThemeProvider: './src/components/ThemeProvider.astro',
        ThemeSelect: './src/components/Empty.astro',
      },
      expressiveCode: {
        themes: ['github-dark'],
        styleOverrides: {
          borderRadius: '12px',
          codeFontFamily: "'SFMono-Regular', Consolas, 'Liberation Mono', monospace",
          codeFontSize: '0.86rem',
          codeBackground: '#22382e',
        },
      },
      sidebar: [
        {
          label: 'Start here',
          items: [
            { label: 'Welcome', link: '/' },
            { label: 'Your first sound', slug: 'getting-started' },
            { label: 'Managers, libraries & keys', slug: 'guides/setup-and-keys' },
            { label: 'Make your first graph', slug: 'guides/your-first-graph' },
          ],
        },
        {
          label: 'Understand your sounds',
          items: [
            { label: 'Reading path', slug: 'guides' },
            { label: 'Events, plays & voices', slug: 'guides/events-plays-voices' },
            { label: 'Change parameters', slug: 'guides/parameters' },
            { label: 'Position & ownership', slug: 'guides/position-and-ownership' },
            { label: 'Stop, pause & clean up', slug: 'guides/stop-and-pause' },
            { label: 'Signals & notifications', slug: 'guides/signals-and-notifications' },
            { label: 'Results & limits', slug: 'guides/results-and-limits' },
            { label: 'Every result and notification', slug: 'guides/outcomes' },
            { label: 'Troubleshooting', slug: 'guides/troubleshooting' },
          ],
        },
        {
          label: 'Build a sound graph',
          collapsed: true,
          items: [
            { label: 'All 49 nodes', slug: 'graph' },
            { label: 'Start, signal, and end', slug: 'graph/lifecycle' },
            { label: 'Choose and play clips', slug: 'graph/clips' },
            { label: 'Parameters and constants', slug: 'graph/parameters' },
            { label: 'Command flow', slug: 'graph/flow' },
            { label: 'Waiting and repeating', slug: 'graph/timing' },
            { label: 'Math and choices', slug: 'graph/math' },
            { label: 'Trim a recording', slug: 'graph/trimming' },
            { label: 'Authoring and settings', slug: 'graph/authoring' },
            { label: 'Validation and debugging', slug: 'graph/validation' },
          ],
        },
        {
          label: 'Advanced integration',
          collapsed: true,
          items: [
            { label: 'Choose an integration path', slug: 'advanced' },
            { label: 'Service and registration', slug: 'advanced/service' },
            { label: 'Clock and voice backend', slug: 'advanced/backend' },
            { label: 'Observe a running graph', slug: 'advanced/observation' },
            { label: 'Parameter declarations', slug: 'advanced/parameter-records' },
          ],
        },
        {
          label: 'API reference',
          collapsed: true,
          items: [
            { label: 'API overview', slug: 'api' },
            { label: 'SoundBus', slug: 'api/sound-bus' },
            { label: 'Play context', slug: 'api/context' },
            { label: 'Parameter values & IDs', slug: 'api/parameters' },
            { label: 'Results & handles', slug: 'api/results-and-handles' },
            { label: 'Owners & groups', slug: 'api/ownership' },
            { label: 'Signals & notifications', slug: 'api/notifications' },
            { label: 'Services & extensions', slug: 'api/services' },
            { label: 'Requests', slug: 'api/requests' },
            { label: 'Scene components', slug: 'api/components' },
            { label: 'Keys & assets', slug: 'api/keys-and-assets' },
            { label: 'Playback settings', slug: 'api/settings' },
            { label: 'Coverage inventory', slug: 'api/coverage' },
          ],
        },
        {
          label: 'Use an example',
          collapsed: true,
          items: [
            { label: 'Choose a recipe', slug: 'recipes' },
            { label: 'Start, loop, and stop', slug: 'recipes/campfire-loop' },
            { label: 'Play one step on the right surface', slug: 'recipes/surface-footsteps' },
            { label: 'Follow a moving sound source', slug: 'recipes/moving-emitter' },
            { label: 'Shape a running sound with parameters', slug: 'recipes/live-parameters' },
            { label: 'Send a command to a running graph', slug: 'recipes/event-signals' },
            {
              label: 'Schedule thunder and cancel the whole storm',
              slug: 'recipes/delayed-thunder',
            },
            { label: 'Switch tools and overlap a hammer tap', slug: 'recipes/workshop-tools' },
            { label: 'Handle busy sounds without a retry storm', slug: 'recipes/playback-limits' },
            { label: 'Crossfade two allowed music tracks', slug: 'recipes/music-crossfade' },
            { label: 'Pause every play in an interaction', slug: 'recipes/pause-interaction' },
            { label: 'Compare Stop and Detach', slug: 'recipes/owner-loss' },
            {
              label: 'Wait for clearance and launch on sound completion',
              slug: 'recipes/launch-on-completion',
            },
          ],
        },
        {
          label: 'Explore the demos',
          items: [
            { label: 'The sound lab', slug: 'demos' },
            { label: 'Unity screenshot library', slug: 'captures' },
            { label: '01 \u00b7 Campfire', slug: 'demos/01-campfire' },
            { label: '02 \u00b7 Footstep', slug: 'demos/02-footstep' },
            { label: '03 \u00b7 Bee', slug: 'demos/03-bee' },
            { label: '04 \u00b7 Engine', slug: 'demos/04-engine' },
            { label: '05 \u00b7 Weather', slug: 'demos/05-weather' },
            { label: '06 \u00b7 Workshop', slug: 'demos/06-workshop' },
            { label: '07 \u00b7 Arcade', slug: 'demos/07-arcade' },
            { label: '08 \u00b7 Jukebox', slug: 'demos/08-jukebox' },
            { label: '09 \u00b7 Portals', slug: 'demos/09-portals' },
            { label: '10 \u00b7 Launch', slug: 'demos/10-launch' },
          ],
        },
      ],
    }),
  ],
});
